# Generated by Django 5.2.8 on 2025-11-18 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('main_information', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('more_information', models.CharField(blank=True, max_length=600, null=True)),
                ('app_flag', models.BooleanField(default=False)),
                ('building_density', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Плотность застройки [домов/га]')),
                ('people_per_building', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Плотность человек в постройке [чел/дом]')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DELETED', 'Deleted'), ('FORMED', 'Formed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название заявки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание заявки')),
                ('territory_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь территории (га)')),
                ('calculated_population', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расчетная численность населения')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.application')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.orders')),
            ],
            options={
                'unique_together': {('application', 'order')},
            },
        ),
    ]
