# Generated by Django 5.2.8 on 2026-01-15 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Расчет плотности', 'verbose_name_plural': 'Расчеты плотности'},
        ),
        migrations.AlterModelOptions(
            name='orderinapplication',
            options={'verbose_name': 'Население в расчете плотности', 'verbose_name_plural': 'Населения в расчетах плотности'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Тип населения', 'verbose_name_plural': 'Типы населения'},
        ),
        migrations.AlterField(
            model_name='application',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_density_calculations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание расчета плотности'),
        ),
        migrations.AlterField(
            model_name='application',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_density_calculations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название расчета плотности'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='building_density',
            field=models.IntegerField(blank=True, help_text='Количество домов на гектар', null=True, verbose_name='Плотность застройки (домов/га)'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='people_per_building',
            field=models.IntegerField(blank=True, help_text='Среднее количество людей в одном доме', null=True, verbose_name='Количество человек в постройке'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=500, verbose_name='URL файла в Minio')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10, verbose_name='Тип файла')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время загрузки')),
                ('clip_embedding', models.BinaryField(blank=True, null=True, verbose_name='Векторное представление CLIP')),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='bmstu_lab.orders', verbose_name='Тип населения')),
            ],
            options={
                'verbose_name': 'Медиа-файл',
                'verbose_name_plural': 'Медиа-файлы',
                'ordering': ['id'],
            },
        ),
    ]
