# Generated by Django 5.2.8 on 2025-11-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderindensitycalculation',
            name='density_calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.densitycalculation'),
        ),
    ]
