# Generated by Django 3.2.25 on 2025-09-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.application')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.orders')),
            ],
            options={
                'unique_together': {('application', 'order')},
            },
        ),
    ]
