# Generated by Django 5.2.8 on 2026-01-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='bmstu_lab_application',
        ),
        migrations.AlterModelTable(
            name='media',
            table='bmstu_lab_media',
        ),
        migrations.AlterModelTable(
            name='orderinapplication',
            table='bmstu_lab_orderindensitycalculation',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='bmstu_lab_orders',
        ),
    ]
