# Generated by Django 3.2.25 on 2025-10-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_orderinapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinapplication',
            old_name='quantity',
            new_name='quantity',
        ),
    ]
