# Generated by Django 3.2.25 on 2025-10-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_rename_quantity_orderinapplication_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderInApplication',
        ),
    ]
