# Generated by Django 3.2.25 on 2025-09-22 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('DELETED', 'Удалён'), ('FORMED', 'Сформирован'), ('COMPLETED', 'Завершён'), ('REJECTED', 'Отклонён')], default='DRAFT', max_length=10, verbose_name='Статус')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('calculated_population', models.IntegerField(blank=True, null=True, verbose_name='Рассчитанная численность')),
                ('client_comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('population_density', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Плотность населения')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь территории')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная услуга')),
                ('calculated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Рассчитанное значение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.order', verbose_name='Заявка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга в заявке',
                'verbose_name_plural': 'Услуги в заявках',
                'unique_together': {('order', 'service')},
            },
        ),
    ]
